server:
  port: ${PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}

spring:
  application:
    name: spring-gift
  thymeleaf:
    prefix:
      classpath:/templates/
    suffix:
      .html
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      schema-locations: classpath:static/sql/schema.sql
      data-locations: classpath:static/sql/data.sql
      mode: embedded
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gift_database
    username: sa
    password:
jwt:
  secretKey: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY:your-api-key}
  redirect-url: ${KAKAO_REDIRECT_URL:http://localhost:8080/oauth/kakao/callback}